apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vvur
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-vvur@sha256:bfb64bf53784d96a1a99808c6ac612899de7638894d1ab35549b5d9c4493f3a6
        name: my-nodejs
        resources: {}
status: {}
