apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vvur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vvur
    app.kubernetes.io/part-of: tkrw-pr712-0075-0003-app
  name: devfile-sample-vvur
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vvur
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vvur
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-vvur@sha256:bfb64bf53784d96a1a99808c6ac612899de7638894d1ab35549b5d9c4493f3a6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
